export const PROPERTY_TYPES = ['Căn Hộ', 'Nhà Phố', 'Biệt Thự', 'Đất Nền'];

export const LOCATIONS = ['Quận 1', 'Quận 2', 'Quận 3', 'Thảo Điền', 'Bình Thạnh'];

export const PRICE_RANGES = [
  { label: 'Dưới 1 Tỷ', min: 0, max: 1 },
  { label: '1 - 3 Tỷ', min: 1, max: 3 },
  { label: '3 - 5 Tỷ', min: 3, max: 5 },
  { label: '5+ Tỷ', min: 5, max: 100 },
];

export const INITIAL_PROPERTIES = [
  {
    id: 1,
    name: 'Biệt Thự Cao Cấp Thảo Điền',
    type: 'Biệt Thự',
    location: 'Thảo Điền',
    price: 15,
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    image: 'https://via.placeholder.com/400x300?text=Property+1',
    featured: true,
  },
  {
    id: 2,
    name: 'Căn Hộ Cao Cấp Quận 1',
    type: 'Căn Hộ',
    location: 'Quận 1',
    price: 5,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    image: 'https://via.placeholder.com/400x300?text=Property+2',
    featured: false,
  },
  {
    id: 3,
    name: 'Nhà Phố 3 Tầng Bình Thạnh',
    type: 'Nhà Phố',
    location: 'Bình Thạnh',
    price: 8,
    bedrooms: 3,
    bathrooms: 2,
    area: 80,
    image: 'https://via.placeholder.com/400x300?text=Property+3',
    featured: true,
  },
  {
    id: 4,
    name: 'Đất Nền Quận 2',
    type: 'Đất Nền',
    location: 'Quận 2',
    price: 3,
    bedrooms: 0,
    bathrooms: 0,
    area: 500,
    image: 'https://via.placeholder.com/400x300?text=Property+4',
    featured: false,
  },
  {
    id: 5,
    name: 'Căn Hộ Dịch Vụ Quận 1',
    type: 'Căn Hộ',
    location: 'Quận 1',
    price: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    image: 'https://via.placeholder.com/400x300?text=Property+5',
    featured: false,
  },
  {
    id: 6,
    name: 'Biệt Thự Hiện Đại Thảo Điền',
    type: 'Biệt Thự',
    location: 'Thảo Điền',
    price: 20,
    bedrooms: 5,
    bathrooms: 4,
    area: 300,
    image: 'https://via.placeholder.com/400x300?text=Property+6',
    featured: true,
  },
];